main: net.simplyvanilla.simplychat.SimplyChatPlugin
name: SimplyChat
description: A simple no frills/thrills chat & reply formatter with papi support.
version: @version@
api-version: 1.19

author: Simply Vanilla
website: https://github.com/SimplyVanilla/SimplyChat

depend:
  - PlaceholderAPI

commands:
  msg:
    description: Private message a player.
    usage: 'Usage: /<command> PLAYER MESSAGE'
    aliases:
      - whisper
      - w
      - tell
      - pm
  reply:
    description: Reply directly to a private message.
    usage: 'Usage: /<command> MESSAGE'
    aliases:
      - r
  ignore:
    description: Ignore a player.
    usage: 'Usage: /<command> PLAYER'
  unignore:
    description: Unignore a player.
    usage: 'Usage: /<command> PLAYER'
  ignorelist:
    description: Get list of ignored players.
    usage: 'Usage: /<command>'
