main: net.simplyvanilla.simplychat.SimplyChatPlugin
name: SimplyChat
version: @version@
api-version: 1.18

depend:
  - PlaceholderAPI

commands:
  message:
    aliases:
      - msg
      - whisper
      - w
      - tell
      - pm
  reply:
    aliases:
      - r
