main: net.simplyvanilla.simplychat.SimplyChatPlugin
name: SimplyChat
version: 0.1.0
api-version: 1.18

depend:
  - PlaceholderAPI

commands:
  message:
    aliases:
      - msg
      - whisper
      - w
      - tell
  reply:
    aliases:
      - r
